version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80" # Production: Map Nginx port 80 to localhost:3000
    # For development, use:
    # ports:
    #   - "5173:5173" # Map Vite dev server port

  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: greatnepalholidays
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
