version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  

  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx ts-node src/index.ts
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_container
    environment:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: greatnepalholidays
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
